#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "contents.h"
#include "filecontents1.h"
#include "filecontents2.h"
#include "filecontents3.h"
#include "filecontents4.h"
#include "filecontents5.h"
#include "filecontents6.h"
int writ() {
    char ch1[50];
    char file1[50];
    char file2[50];
    char file3[50];
    char line1[200];
    char line2[200];
    char line3[200];
    char line4[200];
    char line5[200];
    char line6[200];
    char line7[200];
    char line8[200];
    char line9[200];
    char line10[200];
    char line11[200];
    char line12[200];
    char line13[200];
    char line14[200];
    char line15[200];
    char filename[50];
    printf("You have entered file editor write system.\n");
    conten1();
    printf("\n");
    conten2();
    printf("\n");
    conten3();
    printf("\n");
    conten4();
    printf("\n");
    conten5();
    printf("\n");
    conten6();
    printf("\nSelection: ");
    scanf("%s", ch1);
    printf("\n\nYou have selected ");
    printf("%s", ch1);
    printf(". Now please write the lines:\n");
    printf("1: ");
    scanf("%s", line1);
    printf("2: ");
    scanf("%s", line2);
    printf("3: ");
    scanf("%s", line3);
    printf("4: ");
    scanf("%s", line4);
    printf("5: ");
    scanf("%s", line5);
    printf("6: ");
    scanf("%s", line6);
    printf("7: ");
    scanf("%s", line7);
    printf("8: ");
    scanf("%s", line8);
    printf("9: ");
    scanf("%s", line9);
    printf("10: ");
    scanf("%s", line10);
    printf("11: ");
    scanf("%s", line11);
    printf("12: ");
    scanf("%s", line12);
    printf("13: ");
    scanf("%s", line13);
    printf("14: ");
    scanf("%s", line14);
    printf("15: ");
    scanf("%s", line15);
    printf("\nPlease give this file a name (No Spaces): ");
    scanf("%s", filename);
    FILE * writetable;
    FILE * writefile;
    if(!strcmp("file1", ch1) == 1) {
        writefile = fopen("file1", "w");
        fprintf(writefile, "1: ");
        fprintf(writefile, "%s", line1);
        fprintf(writefile, "\n");
        fprintf(writefile, "2: ");
        fprintf(writefile, "%s", line2);
        fprintf(writefile, "\n");
        fprintf(writefile, "3: ");
        fprintf(writefile, "%s", line3);
        fprintf(writefile, "\n");
        fprintf(writefile, "4: ");
        fprintf(writefile, "%s", line4);
        fprintf(writefile, "\n");
        fprintf(writefile, "5: ");
        fprintf(writefile, "%s", line5);
        fprintf(writefile, "\n");
        fprintf(writefile, "6: ");
        fprintf(writefile, "%s", line6);
        fprintf(writefile, "\n");
        fprintf(writefile, "7: ");
        fprintf(writefile, "%s", line7);
        fprintf(writefile, "\n");
        fprintf(writefile, "8: ");
        fprintf(writefile, "%s", line8);
        fprintf(writefile, "\n");
        fprintf(writefile, "9: ");
        fprintf(writefile, "%s", line9);
        fprintf(writefile, "\n");
        fprintf(writefile, "10: ");
        fprintf(writefile, "%s", line10);
        fprintf(writefile, "\n");
        fprintf(writefile, "11: ");
        fprintf(writefile, "%s", line11);
        fprintf(writefile, "\n");
        fprintf(writefile, "12: ");
        fprintf(writefile, "%s", line12);
        fprintf(writefile, "\n");
        fprintf(writefile, "13: ");
        fprintf(writefile, "%s", line13);
        fprintf(writefile, "\n");
        fprintf(writefile, "14: ");
        fprintf(writefile, "%s", line14);
        fprintf(writefile, "\n");
        fprintf(writefile, "15: ");
        fprintf(writefile, "%s", line15);
        fprintf(writefile, "\n");
        writetable = fopen("file1data.c", "w");
        fprintf(writetable, "#include <stdio.h>\n");
        fprintf(writetable, "#include <string.h>\n");
        fprintf(writetable, "#include <stdlib.h>\n");
        fprintf(writetable, "int conten1(void) {\n");
        fprintf(writetable, "   char file1[50] = \"");
        fprintf(writetable, "%s", filename);
        fprintf(writetable, "\";\n  printf(\"File 1: \");\n   printf(\"\%%s\", file1);");
        fprintf(writetable, "\n}");
    }
    if(!strcmp("file2", ch1) == 1) {
        writefile = fopen("file2", "w");
        fprintf(writefile, "1: ");
        fprintf(writefile, "%s", line1);
        fprintf(writefile, "\n");
        fprintf(writefile, "2: ");
        fprintf(writefile, "%s", line2);
        fprintf(writefile, "\n");
        fprintf(writefile, "3: ");
        fprintf(writefile, "%s", line3);
        fprintf(writefile, "\n");
        fprintf(writefile, "4: ");
        fprintf(writefile, "%s", line4);
        fprintf(writefile, "\n");
        fprintf(writefile, "5: ");
        fprintf(writefile, "%s", line5);
        fprintf(writefile, "\n");
        fprintf(writefile, "6: ");
        fprintf(writefile, "%s", line6);
        fprintf(writefile, "\n");
        fprintf(writefile, "7: ");
        fprintf(writefile, "%s", line7);
        fprintf(writefile, "\n");
        fprintf(writefile, "8: ");
        fprintf(writefile, "%s", line8);
        fprintf(writefile, "\n");
        fprintf(writefile, "9: ");
        fprintf(writefile, "%s", line9);
        fprintf(writefile, "\n");
        fprintf(writefile, "10: ");
        fprintf(writefile, "%s", line10);
        fprintf(writefile, "\n");
        fprintf(writefile, "11: ");
        fprintf(writefile, "%s", line11);
        fprintf(writefile, "\n");
        fprintf(writefile, "12: ");
        fprintf(writefile, "%s", line12);
        fprintf(writefile, "\n");
        fprintf(writefile, "13: ");
        fprintf(writefile, "%s", line13);
        fprintf(writefile, "\n");
        fprintf(writefile, "14: ");
        fprintf(writefile, "%s", line14);
        fprintf(writefile, "\n");
        fprintf(writefile, "15: ");
        fprintf(writefile, "%s", line15);
        fprintf(writefile, "\n");
        writetable = fopen("file2data.c", "w");
        fprintf(writetable, "#include <stdio.h>\n");
        fprintf(writetable, "#include <string.h>\n");
        fprintf(writetable, "#include <stdlib.h>\n");
        fprintf(writetable, "int conten2(void) {\n");
        fprintf(writetable, "   char file2[50] = \"");
        fprintf(writetable, "%s", filename);
        fprintf(writetable, "\";\n  printf(\"File 2: \");\n   printf(\"\%%s\", file2);");
        fprintf(writetable, "\n}");
    }
    if(!strcmp("file3", ch1) == 1) {
        writefile = fopen("file3", "w");
        fprintf(writefile, "1: ");
        fprintf(writefile, "%s", line1);
        fprintf(writefile, "\n");
        fprintf(writefile, "2: ");
        fprintf(writefile, "%s", line2);
        fprintf(writefile, "\n");
        fprintf(writefile, "3: ");
        fprintf(writefile, "%s", line3);
        fprintf(writefile, "\n");
        fprintf(writefile, "4: ");
        fprintf(writefile, "%s", line4);
        fprintf(writefile, "\n");
        fprintf(writefile, "5: ");
        fprintf(writefile, "%s", line5);
        fprintf(writefile, "\n");
        fprintf(writefile, "6: ");
        fprintf(writefile, "%s", line6);
        fprintf(writefile, "\n");
        fprintf(writefile, "7: ");
        fprintf(writefile, "%s", line7);
        fprintf(writefile, "\n");
        fprintf(writefile, "8: ");
        fprintf(writefile, "%s", line8);
        fprintf(writefile, "\n");
        fprintf(writefile, "9: ");
        fprintf(writefile, "%s", line9);
        fprintf(writefile, "\n");
        fprintf(writefile, "10: ");
        fprintf(writefile, "%s", line10);
        fprintf(writefile, "\n");
        fprintf(writefile, "11: ");
        fprintf(writefile, "%s", line11);
        fprintf(writefile, "\n");
        fprintf(writefile, "12: ");
        fprintf(writefile, "%s", line12);
        fprintf(writefile, "\n");
        fprintf(writefile, "13: ");
        fprintf(writefile, "%s", line13);
        fprintf(writefile, "\n");
        fprintf(writefile, "14: ");
        fprintf(writefile, "%s", line14);
        fprintf(writefile, "\n");
        fprintf(writefile, "15: ");
        fprintf(writefile, "%s", line15);
        fprintf(writefile, "\n");
        writetable = fopen("file3data.c", "w");
        fprintf(writetable, "#include <stdio.h>\n");
        fprintf(writetable, "#include <string.h>\n");
        fprintf(writetable, "#include <stdlib.h>\n");
        fprintf(writetable, "int conten3(void) {\n");
        fprintf(writetable, "   char file3[50] = \"");
        fprintf(writetable, "%s", filename);
        fprintf(writetable, "\";\n  printf(\"File 3: \");\n   printf(\"\%%s\", file3);");
        fprintf(writetable, "\n}");
    }
    if(!strcmp("file4", ch1) == 1) {
        writefile = fopen("file4", "w");
        fprintf(writefile, "1: ");
        fprintf(writefile, "%s", line1);
        fprintf(writefile, "\n");
        fprintf(writefile, "2: ");
        fprintf(writefile, "%s", line2);
        fprintf(writefile, "\n");
        fprintf(writefile, "3: ");
        fprintf(writefile, "%s", line3);
        fprintf(writefile, "\n");
        fprintf(writefile, "4: ");
        fprintf(writefile, "%s", line4);
        fprintf(writefile, "\n");
        fprintf(writefile, "5: ");
        fprintf(writefile, "%s", line5);
        fprintf(writefile, "\n");
        fprintf(writefile, "6: ");
        fprintf(writefile, "%s", line6);
        fprintf(writefile, "\n");
        fprintf(writefile, "7: ");
        fprintf(writefile, "%s", line7);
        fprintf(writefile, "\n");
        fprintf(writefile, "8: ");
        fprintf(writefile, "%s", line8);
        fprintf(writefile, "\n");
        fprintf(writefile, "9: ");
        fprintf(writefile, "%s", line9);
        fprintf(writefile, "\n");
        fprintf(writefile, "10: ");
        fprintf(writefile, "%s", line10);
        fprintf(writefile, "\n");
        fprintf(writefile, "11: ");
        fprintf(writefile, "%s", line11);
        fprintf(writefile, "\n");
        fprintf(writefile, "12: ");
        fprintf(writefile, "%s", line12);
        fprintf(writefile, "\n");
        fprintf(writefile, "13: ");
        fprintf(writefile, "%s", line13);
        fprintf(writefile, "\n");
        fprintf(writefile, "14: ");
        fprintf(writefile, "%s", line14);
        fprintf(writefile, "\n");
        fprintf(writefile, "15: ");
        fprintf(writefile, "%s", line15);
        fprintf(writefile, "\n");
        writetable = fopen("file4data.c", "w");
        fprintf(writetable, "#include <stdio.h>\n");
        fprintf(writetable, "#include <string.h>\n");
        fprintf(writetable, "#include <stdlib.h>\n");
        fprintf(writetable, "int conten4(void) {\n");
        fprintf(writetable, "   char file4[50] = \"");
        fprintf(writetable, "%s", filename);
        fprintf(writetable, "\";\n  printf(\"File 4: \");\n   printf(\"\%%s\", file4);");
        fprintf(writetable, "\n}");
    }
    if(!strcmp("file5", ch1) == 1) {
        writefile = fopen("file5", "w");
        fprintf(writefile, "1: ");
        fprintf(writefile, "%s", line1);
        fprintf(writefile, "\n");
        fprintf(writefile, "2: ");
        fprintf(writefile, "%s", line2);
        fprintf(writefile, "\n");
        fprintf(writefile, "3: ");
        fprintf(writefile, "%s", line3);
        fprintf(writefile, "\n");
        fprintf(writefile, "4: ");
        fprintf(writefile, "%s", line4);
        fprintf(writefile, "\n");
        fprintf(writefile, "5: ");
        fprintf(writefile, "%s", line5);
        fprintf(writefile, "\n");
        fprintf(writefile, "6: ");
        fprintf(writefile, "%s", line6);
        fprintf(writefile, "\n");
        fprintf(writefile, "7: ");
        fprintf(writefile, "%s", line7);
        fprintf(writefile, "\n");
        fprintf(writefile, "8: ");
        fprintf(writefile, "%s", line8);
        fprintf(writefile, "\n");
        fprintf(writefile, "9: ");
        fprintf(writefile, "%s", line9);
        fprintf(writefile, "\n");
        fprintf(writefile, "10: ");
        fprintf(writefile, "%s", line10);
        fprintf(writefile, "\n");
        fprintf(writefile, "11: ");
        fprintf(writefile, "%s", line11);
        fprintf(writefile, "\n");
        fprintf(writefile, "12: ");
        fprintf(writefile, "%s", line12);
        fprintf(writefile, "\n");
        fprintf(writefile, "13: ");
        fprintf(writefile, "%s", line13);
        fprintf(writefile, "\n");
        fprintf(writefile, "14: ");
        fprintf(writefile, "%s", line14);
        fprintf(writefile, "\n");
        fprintf(writefile, "15: ");
        fprintf(writefile, "%s", line15);
        fprintf(writefile, "\n");
        writetable = fopen("file5data.c", "w");
        fprintf(writetable, "#include <stdio.h>\n");
        fprintf(writetable, "#include <string.h>\n");
        fprintf(writetable, "#include <stdlib.h>\n");
        fprintf(writetable, "int conten5(void) {\n");
        fprintf(writetable, "   char file5[50] = \"");
        fprintf(writetable, "%s", filename);
        fprintf(writetable, "\";\n  printf(\"File 5: \");\n   printf(\"\%%s\", file5);");
        fprintf(writetable, "\n}");
    }
    if(!strcmp("file6", ch1) == 1) {
        writefile = fopen("file6", "w");
         fprintf(writefile, "1: ");
        fprintf(writefile, "%s", line1);
        fprintf(writefile, "\n");
        fprintf(writefile, "2: ");
        fprintf(writefile, "%s", line2);
        fprintf(writefile, "\n");
        fprintf(writefile, "3: ");
        fprintf(writefile, "%s", line3);
        fprintf(writefile, "\n");
        fprintf(writefile, "4: ");
        fprintf(writefile, "%s", line4);
        fprintf(writefile, "\n");
        fprintf(writefile, "5: ");
        fprintf(writefile, "%s", line5);
        fprintf(writefile, "\n");
        fprintf(writefile, "6: ");
        fprintf(writefile, "%s", line6);
        fprintf(writefile, "\n");
        fprintf(writefile, "7: ");
        fprintf(writefile, "%s", line7);
        fprintf(writefile, "\n");
        fprintf(writefile, "8: ");
        fprintf(writefile, "%s", line8);
        fprintf(writefile, "\n");
        fprintf(writefile, "9: ");
        fprintf(writefile, "%s", line9);
        fprintf(writefile, "\n");
        fprintf(writefile, "10: ");
        fprintf(writefile, "%s", line10);
        fprintf(writefile, "\n");
        fprintf(writefile, "11: ");
        fprintf(writefile, "%s", line11);
        fprintf(writefile, "\n");
        fprintf(writefile, "12: ");
        fprintf(writefile, "%s", line12);
        fprintf(writefile, "\n");
        fprintf(writefile, "13: ");
        fprintf(writefile, "%s", line13);
        fprintf(writefile, "\n");
        fprintf(writefile, "14: ");
        fprintf(writefile, "%s", line14);
        fprintf(writefile, "\n");
        fprintf(writefile, "15: ");
        fprintf(writefile, "%s", line15);
        fprintf(writefile, "\n");
        writetable = fopen("file6data.c", "w");
        fprintf(writetable, "#include <stdio.h>\n");
        fprintf(writetable, "#include <string.h>\n");
        fprintf(writetable, "#include <stdlib.h>\n");
        fprintf(writetable, "int conten6(void) {\n");
        fprintf(writetable, "   char file6[50] = \"");
        fprintf(writetable, "%s", filename);
        fprintf(writetable, "\";\n  printf(\"File 6: \");\n   printf(\"\%%s\", file6);");
        fprintf(writetable, "\n}");
    }
    printf("\nThe operation was successfull!\n");
}